### ISSUE TITLE
numpy 1.24 breaks the code

### ISSUE THREAD

**Issue by yoavatsmonraz** [uw-ipd/RoseTTAFold2NA#46]
Noticed the following error when running the default env yaml - "AttributeError: module 'numpy' has no attribute 'long'"
Post installing numpy 1.23 with python 3.10 it seems to be fine. Suggest updating the yaml ?

**Comment by i-l-sokolov** [comment]
I ran into the same error, and switching to version 1.23 helped! Thank you for providing the fix.

**Comment by yoavatsmonraz** [comment]
sure thing, all the best !

**Comment by fdimaio** [comment]
Sorry about that!  I have just pushed a fix that should work with numpy 1.24 and newer.
